django_templates_project/django_templates_project/django_templates_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("template_app/", include("template_app.urls"))
]

django_templates_project/django_templates_project/template_app/urls.py
from django.urls import path
from . import views

app_name = 'template_app'

urlpatterns = [
    path("", views.index, name="index"),
    path("weather/", views.weather_view, name="weatherview")
]

django_templates_project/django_templates_project/template_app/models.py
from django.db import models

# Create your models here.

django_templates_project/django_templates_project/template_app/views.py
from django.shortcuts import render
from django.http import HttpResponse


# app_name register, {% url app_name:view %}
app_name = "template_app"

def index(request):
    return render(request, "template_app/first.html")

def weather_view(request):
    weather_dict={
        "istanbul" : "30",
        "batman" : "40",
        "paris" : [10,14,17,13],
        "rome": {"morning":10, "evening":12},
        "user_premium": False,
        "test": "Test test Test test"
        }
    return render(request, 'template_app/weather.html', context=weather_dict)

django_templates_project/django_templates_project/template_app/templates/template_app/first.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p>test test</p>
<img src="{% static 'template_app/cat.jpg' %}" width="400px" height="300px" alt="cat" >

{% endblock %}

django_templates_project/django_templates_project/template_app/templates/template_app/weather.html
{% extends 'base.html' %}
{% block content %}
    <h1>Weather Page</h1>
     <!-- jinja -->
     <h4>Istanbul = {{istanbul}}</h4>
     <br>
     <h4>Batman = {{batman}}</h4>
     <br>
     {%for key,value in rome.items %}
     <h4><li>Rome = {{key}} = {{value}}</li></h4>
     {% endfor %}
     <br>
     <ul>
     {% for item in paris %}
        <h4><li>paris = {{item}}</li></h4>
     {% endfor %}
     </ul>
     <br>
     {% if user_premium %}
     <h4> User Premium! </h4>
     {% else %}
     <h4> User Not Premium! </h4>
     {% endif %}
     <br>
     <h4> test = {{test | upper}}</h4>
     <br>
     <h4><a href="{% url 'template_app:index' %}"> go to main page</a></h4>
{% endblock %}

django_templates_project/django_templates_project/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My main website</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
  
        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }
  
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
  
        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }
  
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
  
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
  
        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
  
          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }
  
        .bd-mode-toggle {
          z-index: 1500;
        }
  
        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
        body {
        min-height: 75rem;
        padding-top: 4.5rem;
        }
      </style>
  

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" aria-disabled="true">Weather App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'template_app:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'template_app:weatherview' %}">Link</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>


      {% block content %}
      {% endblock %}

<h1>end of base html</h1>
</body>
</html>